### ISSUE TITLE
Build Fail On Windows

### ISSUE THREAD

**Issue by SwiftGodDev** [Georg-S/AlphaZero#2]
Hi @Georg-S, I tried building it on windows with visual studio code. Cmake generates the build files without any errors but when I run make it gives an error right at the start.

Scanning dependencies of target AlphaZero
[  1%] Building CXX object AlphaZero/CMakeFiles/AlphaZero.dir/src/AlphaZeroTraining.cpp.obj
make[2]: *** [AlphaZero/CMakeFiles/AlphaZero.dir/build.make:83: AlphaZero/CMakeFiles/AlphaZero.dir/src/AlphaZeroTraining.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:239: AlphaZero/CMakeFiles/AlphaZero.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by Georg-S** [comment]
Can you provide further Information?
For example which toolset do you use?

Because building with the Visual Studio toolset works just fine.

**Comment by SwiftGodDev** [comment]
I have visual studio code installed with the c++ extensions. I have also installed the build tools for c++ from the visual studio installer.

**Comment by Georg-S** [comment]
For Windows you need the MSVC, because libtorch is build with the MSVC. 
You can read about it here:
[Libtorch Issue ](https://github.com/pytorch/pytorch/issues/15099)

I will provide an installation guide soon.  (For Windows and Linux)

**Comment by SwiftGodDev** [comment]
Sorry I am a novice in using MSVC. I have used MSVC compiler before once but I do not understand what to do after cmake generates a .sln file.

**Comment by SwiftGodDev** [comment]
@Georg-S I installed Visual Studio 2019 with the c++ build tools as you said. I downloaded SDL2 development libraries for windows. I cant seem to put the SDL2 dir in include path.

Can you please guide me here?

**Comment by SwiftGodDev** [comment]
I finally figured out a way and my build started however Unit_Tests and Main are failing to build and giving this error.

LINK : fatal error LNK1104: cannot open file 'torch-NOTFOUND.obj'

**Comment by Georg-S** [comment]
Which Libtorch do you use, Debug or Release?

If you use release, you have to comment out the line: 	list(APPEND CMAKE_PREFIX_PATH $ENV{Libtorch_DEBUG})
and comment in the line: 	list(APPEND CMAKE_PREFIX_PATH $ENV{Libtorch_RELEASE})

this means remove the # in front of the first line and then add it in front of the other.

After that remove your build and folder and rebuild with Cmake.

And then make sure in Visual Studio you have the same Configuration (Debug / Release) as the library you have included

**Comment by Georg-S** [comment]
And you should not start it out of Visual studio, 
or if you want to start it out of visual studio, you have to set the working directory to the folder, where the .exe is inside

**Comment by Georg-S** [comment]
@SwiftGodDev  If you have further Questions, feel free to ask

**Comment by SwiftGodDev** [comment]
Hi @Georg-S and thank you for your concern. I did the changes in Cmakelists.txt file. I just downloaded the release version of libtorch.

How do I proceed now?

**Comment by Georg-S** [comment]
1. (Git) Pull
2. run the cmake_build.bat
3. open the DeepReinforcement.sln   (Solution) in the build folder
4. Select "Release" as your Build Configuration (Top bar)
5. Build it

Then you should find the executable in build/Main/Release
and you can run it

**Comment by Georg-S** [comment]
@SwiftGodDev 
1. (Git) Pull
2. run the cmake_build.bat
3. open the DeepReinforcement.sln   (Solution) in the build folder
4. Select "Release" as your Build Configuration (Top bar)
5. Build it

Then you should find the executable in build/Main/Release
and you can run it

**Comment by SwiftGodDev** [comment]
Where exactly should the Libtorch_RELEASE environment variable point?

**Comment by Georg-S** [comment]
to your libtorch folder      (in it there is the bin,cmake,include,lib,share,test folder)

**Comment by SwiftGodDev** [comment]
Thank you @Georg-S.

**Comment by Georg-S** [comment]
@SwiftGodDev No Problem, tell me if it works

**Comment by SwiftGodDev** [comment]
Does your code require any specifc version of libtorch?
I have 1.8.1. When I start building it starts giving out a lot of errors.

**Comment by Georg-S** [comment]
Always the same Error?

Can you post the Error Messages?

I use 11_1 but it should work with 1.8.1 too

**Comment by SwiftGodDev** [comment]
It starts giving out this error.

D:\Softwares\libtorch\include\c10/macros/Macros.h(189,20): warning C4067: unexpected tokens following preprocessor directive - expected a newline
4>gtest-all.cc
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::Tensor
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=at::Tensor
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=at::Tensor
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<at::Tensor>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/TensorBody.h(631): message : see reference to class template instantiation 'c10::optional<at::Tensor>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::Tensor
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::Generator
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=at::Generator
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=at::Generator
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<at::Generator>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/TensorBody.h(697): message : see reference to class template instantiation 'c10::optional<at::Generator>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::Generator
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>>' being compiled
2>D:\Softwares\libtorch\include\c10/core/impl/InlineDeviceGuard.h(388): message : see reference to class template instantiation 'c10::optional<c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>>' being compiled
2>D:\Softwares\libtorch\include\c10/core/DeviceGuard.h(168): message : see reference to class template instantiation 'c10::impl::InlineOptionalDeviceGuard<c10::impl::VirtualGuardImpl>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::impl::InlineDeviceGuard<c10::impl::VirtualGuardImpl>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::string
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=std::string
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=std::string
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<std::string>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type_base.h(107): message : see reference to class template instantiation 'c10::optional<std::string>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::string
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(355): message : see reference to class template instantiation 'c10::optional<std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::ShapeSymbol,std::allocator<c10::ShapeSymbol>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(429): message : see reference to class template instantiation 'c10::optional<std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(668): message : see reference to class template instantiation 'c10::VaryingShape<c10::Stride>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::optional<c10::Stride>,std::allocator<c10::optional<c10::Stride>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(429): message : see reference to class template instantiation 'c10::optional<std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(474): message : see reference to class template instantiation 'c10::VaryingShape<int64_t>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<c10::optional<int64_t>,std::allocator<c10::optional<int64_t>>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<int64_t,std::allocator<int64_t>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=std::vector<int64_t,std::allocator<int64_t>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=std::vector<int64_t,std::allocator<int64_t>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<std::vector<int64_t,std::allocator<int64_t>>>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(572): message : see reference to class template instantiation 'c10::optional<std::vector<int64_t,std::allocator<int64_t>>>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=std::vector<int64_t,std::allocator<int64_t>>
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::QualifiedName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=c10::QualifiedName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=c10::QualifiedName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<c10::QualifiedName>' being compiled
2>D:\Softwares\libtorch\include\ATen/core/jit_type.h(907): message : see reference to class template instantiation 'c10::optional<c10::QualifiedName>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::QualifiedName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::OperatorName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=c10::OperatorName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=c10::OperatorName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<c10::OperatorName>' being compiled
2>D:\Softwares\libtorch\include\ATen/record_function.h(266): message : see reference to class template instantiation 'c10::optional<c10::OperatorName>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=c10::OperatorName
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(181,1): warning C4624: 'c10::constexpr_storage_t<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::DimVector
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(361): message : see reference to class template instantiation 'c10::constexpr_storage_t<T>' being compiled
2>        with
2>        [
2>            T=at::DimVector
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to class template instantiation 'c10::trivially_copyable_optimization_optional_base<T>' being compiled
2>        with
2>        [
2>            T=at::DimVector
2>        ]
2>D:\Softwares\libtorch\include\c10/util/Optional.h(418): message : see reference to alias template instantiation 'c10::OptionalBase<at::DimVector>' being compiled
2>D:\Softwares\libtorch\include\ATen/TensorIterator.h(516): message : see reference to class template instantiation 'c10::optional<at::DimVector>' being compiled
2>D:\Softwares\libtorch\include\c10/util/Optional.h(387,1): warning C4624: 'c10::trivially_copyable_optimization_optional_base<T>': destructor was implicitly defined as deleted
2>        with
2>        [
2>            T=at::DimVector
2>        ]

**Comment by SwiftGodDev** [comment]
@Georg-S I am getting the same error with the debug version.

**Comment by Georg-S** [comment]
Those are not errors, those are warnings coming from libtorch, i am getting them aswell.
Do you get any Errors?

In visual studio you can toggle to just see the errors

**Comment by Georg-S** [comment]
@SwiftGodDev 
Those are not errors, those are warnings coming from libtorch, i am getting them aswell. Those are not a problem.
Do you get any Errors?

In visual studio you can toggle to just see the errors

**Comment by SwiftGodDev** [comment]
Sorry @Georg-S as I said I am new to visual studio but thank you for telling me. I will rebuild it and report back to you.

**Comment by Georg-S** [comment]
@SwiftGodDev No Problem

**Comment by SwiftGodDev** [comment]
Hi @Georg-S this is the error I am getting for the projects Unit_test and Main:

LNK1104	cannot open file '\SDL2.lib'

**Comment by Georg-S** [comment]
Have you downloaded SDL2 and SDL2Image and set the enviroment variable?

**Comment by SwiftGodDev** [comment]
Yes @Georg-S I have downloaded them. I have put the paths in VC++ directories for every project.

**Comment by Georg-S** [comment]
Set this Enviroment Variables and you hopefully should be good to go  (but rerun the cmake_build.bat ) and build:

SDL2_INCLUDE_DIRS     -> pointing to for example C:/Users/Georg/Documents/Code/libraries/SDL2/include

SDL2_LIBRARIES       ->pointing to  for example:    C:/Users/Georg/Documents/Code/libraries/SDL2/lib/x64

 SDL2IMAGE_BIN     -> pointing to for example:  C:/Users/Georg/Documents/Code/libraries/SDL2_image/lib/x64

SDL2IMAGE_INCLUDE    -> pointing to for example: C:/Users/Georg/Documents/Code/libraries/SDL2_image/include

**Comment by SwiftGodDev** [comment]
@Georg-S I got a lot of errors this time.
[Error.txt](https://github.com/Georg-S/AlphaZero/files/6305658/Error.txt)

**Comment by Georg-S** [comment]
Those errors are actually new to me.

But you should build the Release version, since you are using the release version of libtorch, don't you?

**Comment by Georg-S** [comment]
Did you setup QT5 ?

**Comment by Georg-S** [comment]
Sry my bad, the last Enviroment Variable you have to set:

-	QT_64_MSVC2017		pointing to for example C:\Qt\Qt5.14.2\5.14.2\msvc2017_64

**Comment by SwiftGodDev** [comment]
I changed to debug version

**Comment by Georg-S** [comment]
Then you have to comment out one Line in the CMakeLists.txt and comment in the other, as described way above ^^.

**Comment by SwiftGodDev** [comment]
Yes thats done

**Comment by Georg-S** [comment]
Sadly i can't help you there, if you install QT it should be there.

**Comment by SwiftGodDev** [comment]
Can you please tell the way you downloaded and installed Qt

**Comment by SwiftGodDev** [comment]
Are you talking about Qt Visual Studio tools?

If yes, I hadnt installed them. I installed them now so now I should have a folder.

**Comment by Georg-S** [comment]
Don't actually know anymore where i downloaded it but  [this](https://www.qt.io/download-qt-installer?hsCtaTracking=99d9dd4f-5681-48d2-b096-470725510d34%7C074ddad0-fdef-4e53-8aa8-5e8a876d6ab4)  seems to be right

(Back then i downloaded Version 5.14.2)

**Comment by SwiftGodDev** [comment]
I understood why I dont have the folder. I installed Qt for MingW. The online installer checked my system and installed qt for mingw.

**Comment by Georg-S** [comment]
Okay makes sense

**Comment by SwiftGodDev** [comment]
Hi @Georg-S the solution got built without any errors but when I run main.exe it gives this error.

Program: Qt5Cored.dll
This application failed to start because no Qt platform plugin could be initialized.

**Comment by SwiftGodDev** [comment]
I got it running finally.

But when I start a game of chess against the minimax AI I cant play after it plays.

Please rectify.

**Comment by SwiftGodDev** [comment]
I will close this issue as problem is resolved and open a new one.

**Comment by Georg-S** [comment]
@SwiftGodDev 
Finally :D
