### ISSUE TITLE
Cant Play Against Chess MiniMax AI

### ISSUE THREAD

**Issue by SwiftGodDev** [Georg-S/AlphaZero#3]
When I start a game against the minimax AI I cant make a move after the AI makes a move. I tried playing from both colors.

**Comment by Georg-S** [comment]
@SwiftGodDev 
Issue is confirmed, will fix it soon

**Comment by Georg-S** [comment]
![image](https://user-images.githubusercontent.com/48867355/114745936-7bcde380-9d4f-11eb-9a2e-3f6e285a8675.png)
That's why having no Brackets in a single line if can be a Problem :)

**Comment by Georg-S** [comment]
@SwiftGodDev 

Fixed it, thanks for reporting

**Comment by SwiftGodDev** [comment]
Thank you @Georg-S.
